site_name: WSIN.govbr
site_description: Biblioteca para acessar o webservice da Imprensa Nacional para publicação e acompanhamento de envio de matérias para o Diário Oficial da União.
theme: readthedocs
repo_url: https://github.com/govbr/wsin.govbr
